theme: jekyll-theme-cayman
title: 'Belarusian Victims of Chernobyl'
description: 'The Belarusian Victims of Chernobyl charity was set up in South Wiltshire UK in 2001 to fund projects, to provide humanitarian and medical aid and to support sick and vulnerable children in the Republic of Belarus.'
